In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, HTML
import time

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 10000)
pd.set_option('display.colheader_justify', 'center')
pd.set_option('display.precision', 2)


def query(question, dataframe_name, output):
    time_start = time.time()
    time_elapsed = time.time() - time_start
    display(HTML(f'<code>{dataframe_name} response time: {time_elapsed:.02f} sec</code>'))
    display(HTML(f'<strong>Analysing:</strong> {question}'))
    display(HTML(f'<strong>Result:</strong> {output} <hr><br>'))

In [2]:
def query_grouped(question, dataframe_name, output):
    time_start = time.time()
    # Convert the Series to DataFrame if it's not already a DataFrame
    if isinstance(output, pd.Series):
        output = output.to_frame()
    output_html = output.to_html()
    time_elapsed = time.time() - time_start
    display(HTML(f'<code>{dataframe_name} response time: {time_elapsed:.02f} sec</code>'))
    display(HTML(f'<strong>Analysing:</strong> {question}'))
    display(HTML(f'<strong>Result:</strong> {output_html} <hr><br>'))

In [ ]:
"""
csv_files = [
    './June_2018.csv',
    './June_2019.csv',
    './June_2020.csv',
    './June_2021.csv',
    './June_2022.csv',
    './June_2023.csv'
]

df_list = []

for csv_file in csv_files:
    df_weather = pd.read_csv(csv_file, low_memory=False)
    df_list.append(df_weather)


df_weather_combined = pd.concat(df_list, ignore_index=True)
df_weather_combined.to_csv('./weather_combined_march.csv', index=False)

"""

In [4]:
df_weather = pd.read_csv('./weather_combined_june.csv', low_memory=False)
df_weather['UTC_DATE'] = pd.to_datetime(df_weather['UTC_DATE'], utc=True)
df_weather['LOCAL_DATE'] = df_weather['UTC_DATE'].dt.tz_convert('America/New_York')
df_weather['LOCAL_DATE'] = df_weather['LOCAL_DATE'].dt.strftime('%Y-%m-%d')

In [5]:
#df_year = df_weather[(df_weather['LOCAL_DATE'] != '2020-01-10')] # Ontario Wind And Rainn

df_year = df_weather.groupby(['LOCAL_YEAR'])["WIND_SPEED"].mean().reset_index()
display(df_year)

   LOCAL_YEAR  WIND_SPEED
0     2018        10.96
1     2019        11.32
2     2020        10.97
3     2021        10.70
4     2022        12.21
5     2023        10.11

In [6]:
df_station = df_weather.groupby(['LOCAL_HOUR', 'LOCAL_DATE'])[
    "WIND_SPEED"].mean().reset_index()
display(df_station)

    LOCAL_HOUR  WIND_SPEED
0        0          8.65
1        1          8.55
2        2          8.52
3        3          8.49
4        4          8.51
5        5          8.57
6        6          9.09
7        7         10.30
8        8         11.31
9        9         12.08
10      10         12.85
11      11         13.59
12      12         14.10
13      13         14.56
14      14         14.80
15      15         14.75
16      16         14.55
17      17         14.07
18      18         13.14
19      19         11.60
20      20          9.85
21      21          9.02
22      22          8.74
23      23          8.69